"""Añadir tablas CaSector y CaOrganismo y relacionar con Licitacion

Revision ID: 2df9307d86aa
Revises: 3bc3e2447bde
Create Date: 2025-11-06 20:42:35.832548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2df9307d86aa'
down_revision: Union[str, Sequence[str], None] = '3bc3e2447bde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ca_sector',
    sa.Column('sector_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('sector_id')
    )
    op.create_index(op.f('ix_ca_sector_nombre'), 'ca_sector', ['nombre'], unique=True)
    op.create_table('ca_organismo',
    sa.Column('organismo_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=1000), nullable=False),
    sa.Column('sector_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sector_id'], ['ca_sector.sector_id'], ),
    sa.PrimaryKeyConstraint('organismo_id')
    )
    op.create_index(op.f('ix_ca_organismo_nombre'), 'ca_organismo', ['nombre'], unique=True)
    op.add_column('ca_licitacion', sa.Column('organismo_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ca_licitacion', 'ca_organismo', ['organismo_id'], ['organismo_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ca_licitacion', type_='foreignkey')
    op.drop_column('ca_licitacion', 'organismo_id')
    op.drop_index(op.f('ix_ca_organismo_nombre'), table_name='ca_organismo')
    op.drop_table('ca_organismo')
    op.drop_index(op.f('ix_ca_sector_nombre'), table_name='ca_sector')
    op.drop_table('ca_sector')
    # ### end Alembic commands ###
