"""Creación inicial de todas las tablas

Revision ID: 3bc3e2447bde
Revises: 
Create Date: 2025-11-06 18:27:57.403806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bc3e2447bde'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ca_licitacion',
    sa.Column('ca_id', sa.Integer(), nullable=False),
    sa.Column('codigo_ca', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=1000), nullable=True),
    sa.Column('monto_clp', sa.Float(), nullable=True),
    sa.Column('fecha_publicacion', sa.Date(), nullable=True),
    sa.Column('fecha_cierre', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estado_ca_texto', sa.String(length=255), nullable=True),
    sa.Column('proveedores_cotizando', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('direccion_entrega', sa.String(length=1000), nullable=True),
    sa.Column('productos_solicitados', sa.JSON(), nullable=True),
    sa.Column('puntuacion_final', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('ca_id')
    )
    op.create_index(op.f('ix_ca_licitacion_codigo_ca'), 'ca_licitacion', ['codigo_ca'], unique=True)
    op.create_index(op.f('ix_ca_licitacion_puntuacion_final'), 'ca_licitacion', ['puntuacion_final'], unique=False)
    op.create_table('ca_seguimiento',
    sa.Column('ca_id', sa.Integer(), nullable=False),
    sa.Column('es_favorito', sa.Boolean(), nullable=False),
    sa.Column('es_ofertada', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ca_id'], ['ca_licitacion.ca_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ca_id')
    )
    op.create_index(op.f('ix_ca_seguimiento_es_favorito'), 'ca_seguimiento', ['es_favorito'], unique=False)
    op.create_index(op.f('ix_ca_seguimiento_es_ofertada'), 'ca_seguimiento', ['es_ofertada'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ca_seguimiento_es_ofertada'), table_name='ca_seguimiento')
    op.drop_index(op.f('ix_ca_seguimiento_es_favorito'), table_name='ca_seguimiento')
    op.drop_table('ca_seguimiento')
    op.drop_index(op.f('ix_ca_licitacion_puntuacion_final'), table_name='ca_licitacion')
    op.drop_index(op.f('ix_ca_licitacion_codigo_ca'), table_name='ca_licitacion')
    op.drop_table('ca_licitacion')
    # ### end Alembic commands ###
