"""Agrega fecha_cierre_segundo_llamado

Revision ID: 8ce4f5dd5336
Revises: fab8786612ca
Create Date: 2025-11-08 16:42:45.757415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ce4f5dd5336'
down_revision: Union[str, Sequence[str], None] = 'fab8786612ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ca_licitacion', sa.Column('fecha_cierre_segundo_llamado', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ca_licitacion', 'fecha_cierre_segundo_llamado')
    # ### end Alembic commands ###
