"""Reemplaza CaOrganismoPrioritario por CaOrganismoRegla

Revision ID: 9733f9599c89
Revises: a9c870c2fa74
Create Date: 2025-11-11 20:16:02.782872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9733f9599c89'
down_revision: Union[str, Sequence[str], None] = 'a9c870c2fa74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ca_organismo_regla',
    sa.Column('regla_id', sa.Integer(), nullable=False),
    sa.Column('organismo_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('PRIORITARIO', 'NO_DESEADO', name='tipo_regla_organismo_enum', native_enum=False), nullable=False),
    sa.Column('puntos', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['organismo_id'], ['ca_organismo.organismo_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('regla_id')
    )
    op.create_index(op.f('ix_ca_organismo_regla_organismo_id'), 'ca_organismo_regla', ['organismo_id'], unique=True)
    op.create_index(op.f('ix_ca_organismo_regla_tipo'), 'ca_organismo_regla', ['tipo'], unique=False)
    op.drop_table('ca_organismo_prioritario')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ca_organismo_prioritario',
    sa.Column('org_prio_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('organismo_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('puntos', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['organismo_id'], ['ca_organismo.organismo_id'], name=op.f('ca_organismo_prioritario_organismo_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('org_prio_id', name=op.f('ca_organismo_prioritario_pkey')),
    sa.UniqueConstraint('organismo_id', name=op.f('ca_organismo_prioritario_organismo_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_index(op.f('ix_ca_organismo_regla_tipo'), table_name='ca_organismo_regla')
    op.drop_index(op.f('ix_ca_organismo_regla_organismo_id'), table_name='ca_organismo_regla')
    op.drop_table('ca_organismo_regla')
    # ### end Alembic commands ###
