"""Agregar columnas faltantes como monto_clp

Revision ID: a9c870c2fa74
Revises: 8ce4f5dd5336
Create Date: 2025-11-11 19:22:43.327246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9c870c2fa74'
down_revision: Union[str, Sequence[str], None] = '8ce4f5dd5336'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
