"""Añadir tablas CaKeyword y CaOrganismoPrioritario

Revision ID: fab8786612ca
Revises: 2df9307d86aa
Create Date: 2025-11-06 21:49:59.791547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fab8786612ca'
down_revision: Union[str, Sequence[str], None] = '2df9307d86aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ca_keyword',
    sa.Column('keyword_id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('puntos', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('keyword_id')
    )
    op.create_index(op.f('ix_ca_keyword_keyword'), 'ca_keyword', ['keyword'], unique=True)
    op.create_index(op.f('ix_ca_keyword_tipo'), 'ca_keyword', ['tipo'], unique=False)
    op.create_table('ca_organismo_prioritario',
    sa.Column('org_prio_id', sa.Integer(), nullable=False),
    sa.Column('organismo_id', sa.Integer(), nullable=False),
    sa.Column('puntos', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organismo_id'], ['ca_organismo.organismo_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('org_prio_id'),
    sa.UniqueConstraint('organismo_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ca_organismo_prioritario')
    op.drop_index(op.f('ix_ca_keyword_tipo'), table_name='ca_keyword')
    op.drop_index(op.f('ix_ca_keyword_keyword'), table_name='ca_keyword')
    op.drop_table('ca_keyword')
    # ### end Alembic commands ###
